FidelCly/api

- .github/dependabot.yml
- .github/workflows/dependabot_auto-merge.yml
- Add dependabot config for vulnerability alerting
- Add dependabot auto-merge workflow
> feat(dependabot): enable vulnerability alerts

- docker-compose.yml
- *describe your work here ...*
- ajout de admirer pour les visionner la db durant les test en local
-
[FID-]
> add admirer for api testing

- src/controllers/shop.controller.ts
- src/controllers/user.controller.ts
- src/data-source.ts
- src/repositories/shop.repository.ts
- src/repositories/user.repository.ts
- src/routes/index.ts
- src/routes/shop.routes.ts
- src/routes/user.routes.ts
- src/tests/controllers/card.controller.test.ts
- src/tests/controllers/shop.controller.test.ts
- src/tests/controllers/user.controller.test.ts
- src/tests/factory.ts
- Refactor wallet route
- Add route to get all shops
[FID-54]
[FID-54]: https://msc-etna.atlassian.net/browse/FID-54?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(wallet): refactor wallet route and add tests

- Procfile
- package.json
- src/data-source.ts
- start.sh
- tsconfig.json
- Add database url to data source config
- Add Procfile
[FID-]
> feat(deployment): add database url to data source config and Procfile

- src/controllers/card.controller.ts
- src/controllers/index.ts
- src/controllers/promotion.controller.ts
- src/entities/card.ts
- src/entities/index.ts
- src/entities/promotion.ts
- src/entities/shop.ts
- src/migrations/1671221397845-AddPromotionTable.ts
- src/payloads/card.payload.ts
- src/payloads/index.ts
- src/payloads/promotion.payload.ts
- src/repositories/index.ts
- src/repositories/promotion.repository.ts
- src/routes/index.ts
- src/routes/promotion.routes.ts
- src/tests/controllers/card.controller.test.ts
- src/tests/controllers/promotion.controller.test.ts
- src/tests/controllers/shop.controller.test.ts
- src/tests/controllers/user.controller.test.ts
- src/tests/factory.ts
- src/tests/seeds/card.seed.ts
- src/tests/seeds/index.ts
- src/tests/seeds/promotion.seed.ts
- src/tests/seeds/shop.seed.ts
- src/tests/seeds/user.seed.ts
- Add Promotion entity, repositroy and controller
- Write unit tests for `PromotionController`
- Refactor unit tests of other controllers
[FID-63]
[FID-63]: https://msc-etna.atlassian.net/browse/FID-63?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: implement promotions logic

- README.md
- src/controllers/shop.controller.ts
- src/entities/shop.ts
- src/tests/controllers/shop.controller.test.ts
- src/tests/factory.ts
- src/tests/seeds/index.ts
- src/tests/seeds/shop.seed.ts
- src/utils/geoloc.utils.ts
- Implement algorithm
- Update readme
- Write test
[FID-68]
[FID-68]: https://msc-etna.atlassian.net/browse/FID-68?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: implement algorithm to compute distance between two geoloc points

- .npmignore
- Procfile
- package.json
- start.sh
- Apply migrations post deploy
- Add `.npmignore` file to ignore tests folder
[FID-]
> fix: apply migrations post deployment

- README.md
- src/entities/index.ts
- src/entities/shop.ts
- src/migrations/1675344154445-AddShopActivity.ts
- src/payloads/shop.payload.ts
- src/tests/seeds/shop.seed.ts
- Add field on entity
- Update payloads and seeds
- Update Readme
- Generate migration
[FID-73]
[FID-73]: https://msc-etna.atlassian.net/browse/FID-73?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add activity type on shops entity

- README.md
- src/controllers/shop.controller.ts
- src/repositories/shop.repository.ts
- src/routes/shop.routes.ts
- src/tests/controllers/shop.controller.test.ts
- Add route to fetch a shop's clients
- Fix shop's delete route to delete relations
- Add test for shop's clients
- Add query param to fetch active shops only
- Update readme
[FID-107]
[FID-107]: https://msc-etna.atlassian.net/browse/FID-107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add route to fetch a shop's clients

- package-lock.json
- src/auth/auth.pb.ts
- return uuid on login
[FID-142]
[FID-142]: https://msc-etna.atlassian.net/browse/FID-142?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: return uuid on login

- README.md
- update code changes introduction on readme
- 
-
[FID-]
> fix: update code changes introduction on readme

- src/user/user.dto.ts
- src/user/user.entity.ts
- src/user/user.enum.ts
- add user profile information
[FID-136]
[FID-136]: https://msc-etna.atlassian.net/browse/FID-136?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add user profile information

- src/auth/ability.factory.ts
- fix  fider ability when shop doesn't exist
- 
-
[FID-]
> fix: fider ability when shop doesn't exist

- src/auth/ability.factory.ts
- src/auth/auth.guard.ts
-  add condition on fider ability
- 
-
[FID-]
> fix: add condition on fider ability

- README.md
- package-lock.json
- src/analytics/card.pb.ts
- src/app.controller.ts
- src/app.dto.ts
- src/app.module.ts
- src/balance/balance.controller.ts
- src/balance/balance.service.ts
- src/card/card.dto.ts
- src/card/card.entity.ts
- src/card/card.service.ts
- test/app.e2e-spec.ts
- test/app.seed.ts
- test/balance/balance.e2e-spec.ts
- test/card/card.seed.ts
- rewrite checkout endpoint
- write tests
- update readme
- remove `startAt` and `endAt` from `card`
[FID-137]
[FID-137]: https://msc-etna.atlassian.net/browse/FID-137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: checkout endpoint

- README.md
- src/auth/auth.guard.ts
- src/user/user.controller.ts
- src/user/user.service.ts
- test/card/card.seed.ts
- test/user/user.e2e-spec.ts
- Adding a routes that get all users cards
[FID-162]
[FID-162]: https://msc-etna.atlassian.net/browse/FID-162?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add user cards routes

- src/user/user.service.ts
- Adding shop relation in "getUserCards" routes
> Feat: add shop realation

- src/shop/shop.dto.ts
- src/shop/shop.entity.ts
- src/user/user.dto.ts
- src/user/user.entity.ts
> feat: add photoUrl propery

- src/user/user.service.ts
> feat: promotion relations

- src/app.controller.ts
- check promotion date and (de)activate the promotion accordingly
- 
-
[FID-171]
[FID-171]: https://msc-etna.atlassian.net/browse/FID-171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: check promotion date and (de)activate the promotion accordingly

- src/promotion/promotion.dto.ts
- check if checkout limit is greater than 0
- 
-
[FID-160]
[FID-160]: https://msc-etna.atlassian.net/browse/FID-160?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: check if checkout limit is greater than 0

- src/card/card.controller.ts
- src/card/card.entity.ts
- test/card/card.e2e-spec.ts
- forbid creation of the same card twice
- 
-
[FID-167]
[FID-167]: https://msc-etna.atlassian.net/browse/FID-167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: forbid creation of the same card twice

- README.md
- src/card/card.service.ts
- src/user/user.controller.ts
- user cards fetch
- 
-
[FID-]
> fix: user cards fetch

- src/shop/shop.service.ts
Adding relations promtions & cards in shop entitiy
> feat: adding relations promtions & cards in shop entitiy

- src/exception.interceptor.ts
> fix: catch error 500

- src/app.controller.ts
- add await in checkout
- 
-
[FID-]
> fix: add await in checkout

- src/app.controller.ts
- src/campaign/campaign.controller.ts
- refactor checkout for visiblity and remove console log
- 
-
[FID-]
> fix: refactor checkout for visiblity and remove console log
